/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package atm_application;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.JOptionPane;

/**
 *
 * @author SidhalingSwami
 */
public class Fastcash extends javax.swing.JFrame {

    /**
     * Creates new form fastcash
     */
    public Fastcash() {
        initComponents();
    }
    
    int MyAccNo;
    int MyBal;
    public Fastcash(int AccNum) {
        initComponents();
        MyAccNo = AccNum;
        MyBal = getBalance();
        BalLbl.setText(""+MyBal);
    }
    
    //method to get balance by using account number
    Connection con = null;
    PreparedStatement pst = null;
    ResultSet rs = null;
    Statement st = null;
    private int getBalance(){
        int balance = 0;
        String query = "select Balance from AccountTbl where AccNo='"+MyAccNo+"'";
            try {
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vjti_atm", "root", "root");
                st = con.createStatement();
                rs = st.executeQuery(query);
                System.out.println("query is : "+rs.toString());
                if(rs.next()){
                    balance = rs.getInt(1);
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
        return balance;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        W100Btn = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        W500Btn = new javax.swing.JButton();
        W5000Btn = new javax.swing.JButton();
        W2000Btn = new javax.swing.JButton();
        W10000Btn = new javax.swing.JButton();
        W1000Btn = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        BalLbl = new javax.swing.JLabel();
        GoBackBtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));

        jPanel3.setBackground(new java.awt.Color(0, 102, 102));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 20)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Please Select Your Transaction..");

        jLabel4.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("VJTI ATM Application");

        ExitBtn.setBackground(new java.awt.Color(255, 255, 255));
        ExitBtn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        ExitBtn.setForeground(new java.awt.Color(204, 0, 0));
        ExitBtn.setText("X");
        ExitBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ExitBtnMouseClicked(evt);
            }
        });
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(225, 225, 225)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel3)
                        .addContainerGap())
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE))))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(ExitBtn)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(29, 29, 29))
        );

        jLabel5.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 204, 0));
        jLabel5.setText("Your Current Balance is:");

        W100Btn.setBackground(new java.awt.Color(255, 255, 255));
        W100Btn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        W100Btn.setForeground(new java.awt.Color(0, 102, 102));
        W100Btn.setText("100");
        W100Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                W100BtnMouseClicked(evt);
            }
        });
        W100Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                W100BtnActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 10)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("CopyRights: @SidhalingSwami");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addContainerGap())
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel1))
        );

        W500Btn.setBackground(new java.awt.Color(255, 255, 255));
        W500Btn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        W500Btn.setForeground(new java.awt.Color(0, 102, 102));
        W500Btn.setText("500");
        W500Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                W500BtnMouseClicked(evt);
            }
        });
        W500Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                W500BtnActionPerformed(evt);
            }
        });

        W5000Btn.setBackground(new java.awt.Color(255, 255, 255));
        W5000Btn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        W5000Btn.setForeground(new java.awt.Color(0, 102, 102));
        W5000Btn.setText("5000");
        W5000Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                W5000BtnMouseClicked(evt);
            }
        });
        W5000Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                W5000BtnActionPerformed(evt);
            }
        });

        W2000Btn.setBackground(new java.awt.Color(255, 255, 255));
        W2000Btn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        W2000Btn.setForeground(new java.awt.Color(0, 102, 102));
        W2000Btn.setText("2000");
        W2000Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                W2000BtnMouseClicked(evt);
            }
        });
        W2000Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                W2000BtnActionPerformed(evt);
            }
        });

        W10000Btn.setBackground(new java.awt.Color(255, 255, 255));
        W10000Btn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        W10000Btn.setForeground(new java.awt.Color(0, 102, 102));
        W10000Btn.setText("10000");
        W10000Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                W10000BtnMouseClicked(evt);
            }
        });
        W10000Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                W10000BtnActionPerformed(evt);
            }
        });

        W1000Btn.setBackground(new java.awt.Color(255, 255, 255));
        W1000Btn.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        W1000Btn.setForeground(new java.awt.Color(0, 102, 102));
        W1000Btn.setText("1000");
        W1000Btn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                W1000BtnMouseClicked(evt);
            }
        });
        W1000Btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                W1000BtnActionPerformed(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Arial", 0, 30)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(0, 102, 102));
        jLabel6.setText("Fastcash");

        BalLbl.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        BalLbl.setForeground(new java.awt.Color(51, 204, 0));
        BalLbl.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                BalLblMouseClicked(evt);
            }
        });

        GoBackBtn.setBackground(new java.awt.Color(255, 255, 255));
        GoBackBtn.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        GoBackBtn.setForeground(new java.awt.Color(0, 102, 102));
        GoBackBtn.setText("BACK");
        GoBackBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                GoBackBtnMouseClicked(evt);
            }
        });
        GoBackBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoBackBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(W2000Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(W100Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addComponent(W5000Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(W10000Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                            .addComponent(W500Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGap(50, 50, 50)
                            .addComponent(W1000Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addGap(125, 125, 125))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addComponent(jLabel5)
                        .addGap(18, 18, 18)
                        .addComponent(BalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 104, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(316, 316, 316)
                        .addComponent(GoBackBtn)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(43, 43, 43)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BalLbl, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(41, 41, 41)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(W1000Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(W500Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(W100Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(60, 60, 60)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(W5000Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(W10000Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(W2000Btn, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addComponent(GoBackBtn)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void W100BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_W100BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_W100BtnActionPerformed

    private void W500BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_W500BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_W500BtnActionPerformed

    private void W5000BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_W5000BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_W5000BtnActionPerformed

    private void W2000BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_W2000BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_W2000BtnActionPerformed

    private void W10000BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_W10000BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_W10000BtnActionPerformed

    private void W1000BtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_W1000BtnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_W1000BtnActionPerformed

    private void ExitBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ExitBtnMouseClicked
        System.exit(0);
    }//GEN-LAST:event_ExitBtnMouseClicked
    
    
    //method to put transaction Entry
    private void WithdrwalEntry(int Amount){
        try{
               Utility ut = new Utility();
               con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vjti_atm", "root", "root");
               PreparedStatement Add = con.prepareStatement("insert into transactiontbl (AccNum, Type, Amount, Date) values(?,?,?,?)");
//               Add.setInt(1, 1);
               Add.setString(1, ""+MyAccNo);
               Add.setString(2, "Withdrwal");
               Add.setString(3, ""+Amount);
               Add.setString(4, ut.getDate());
               
               
               int row = Add.executeUpdate();
//               JOptionPane.showMessageDialog(this, "Account is created successfuly..!");
               con.close();
           }catch(Exception e){
               JOptionPane.showMessageDialog(this, e);
           }
    }
    
    
    private void W100BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_W100BtnMouseClicked
        if(MyBal < 100){
            JOptionPane.showMessageDialog(this, "OPPs.. Not Enough Balance..!");
        }
        else{
            try {
                String query = "update AccountTbl set Balance=? where AccNo=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vjti_atm", "root", "root");
                pst = con.prepareStatement(query);
                int remBal = MyBal-100;
                pst.setInt(1, remBal);
                pst.setInt(2, MyAccNo);
                if(pst.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this, " Transaction Successful:)");
                    WithdrwalEntry(100);
                    new Balance(MyAccNo).setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "missing Information..!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
            
        }
    }//GEN-LAST:event_W100BtnMouseClicked

    private void W500BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_W500BtnMouseClicked
        if(MyBal < 500){
            JOptionPane.showMessageDialog(this, "OPPs.. Not Enough Balance..!");
        }
        else{
            try {
                String query = "update AccountTbl set Balance=? where AccNo=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vjti_atm", "root", "root");
                pst = con.prepareStatement(query);
                int remBal = MyBal-500;
                System.out.println("old balance is :"+MyBal);
                pst.setInt(1, remBal);
                pst.setInt(2, MyAccNo);
                if(pst.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this, " Transaction Successful:)");
                    WithdrwalEntry(500);
                    new Balance(MyAccNo).setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "missing Information..!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
            
        }
    }//GEN-LAST:event_W500BtnMouseClicked

    private void W1000BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_W1000BtnMouseClicked
        if(MyBal < 1000){
            JOptionPane.showMessageDialog(this, "OPPs.. Not Enough Balance..!");
        }
        else{
            try {
                String query = "update AccountTbl set Balance=? where AccNo=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vjti_atm", "root", "root");
                pst = con.prepareStatement(query);
                int remBal = MyBal-1000;
                System.out.println("old balance is :"+MyBal);
                pst.setInt(1, remBal);
                pst.setInt(2, MyAccNo);
                if(pst.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this, " Transaction Successful:)");
                    WithdrwalEntry(1000);
                    new Balance(MyAccNo).setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "missing Information..!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
            
        }
    }//GEN-LAST:event_W1000BtnMouseClicked

    private void W2000BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_W2000BtnMouseClicked
        if(MyBal < 2000){
            JOptionPane.showMessageDialog(this, "OPPs.. Not Enough Balance..!");
        }
        else{
            try {
                String query = "update AccountTbl set Balance=? where AccNo=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vjti_atm", "root", "root");
                pst = con.prepareStatement(query);
                int remBal = MyBal-2000;
                System.out.println("old balance is :"+MyBal);
                pst.setInt(1, remBal);
                pst.setInt(2, MyAccNo);
                if(pst.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this, " Transaction Successful:)");
                    WithdrwalEntry(2000);
                    new Balance(MyAccNo).setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "missing Information..!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
            
        }
    }//GEN-LAST:event_W2000BtnMouseClicked

    private void W5000BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_W5000BtnMouseClicked
        if(MyBal < 5000){
            JOptionPane.showMessageDialog(this, "OPPs.. Not Enough Balance..!");
        }
        else{
            try {
                String query = "update AccountTbl set Balance=? where AccNo=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vjti_atm", "root", "root");
                pst = con.prepareStatement(query);
                int remBal = MyBal-5000;
                System.out.println("old balance is :"+MyBal);
                pst.setInt(1, remBal);
                pst.setInt(2, MyAccNo);
                if(pst.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this, " Transaction Successful:)");
                    WithdrwalEntry(5000);
                    new Balance(MyAccNo).setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "missing Information..!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
            
        }
    }//GEN-LAST:event_W5000BtnMouseClicked

    private void W10000BtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_W10000BtnMouseClicked
        if(MyBal < 10000){
            JOptionPane.showMessageDialog(this, "OPPs.. Not Enough Balance..!");
        }
        else{
            try {
                String query = "update AccountTbl set Balance=? where AccNo=?";
                con = DriverManager.getConnection("jdbc:mysql://localhost:3306/vjti_atm", "root", "root");
                pst = con.prepareStatement(query);
                int remBal = MyBal-10000;
                System.out.println("old balance is :"+MyBal);
                pst.setInt(1, remBal);
                pst.setInt(2, MyAccNo);
                if(pst.executeUpdate() == 1){
                    JOptionPane.showMessageDialog(this, " Transaction Successful:)");
                    WithdrwalEntry(10000);
                    new Balance(MyAccNo).setVisible(true);
                    this.dispose();
                }
                else{
                    JOptionPane.showMessageDialog(this, "missing Information..!");
                }
            } catch (Exception e) {
                JOptionPane.showMessageDialog(this, e);
            }
            
        }
    }//GEN-LAST:event_W10000BtnMouseClicked

    private void GoBackBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_GoBackBtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_GoBackBtnMouseClicked

    private void GoBackBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoBackBtnActionPerformed
        new Main_Menu().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_GoBackBtnActionPerformed

    private void BalLblMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_BalLblMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_BalLblMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Fastcash.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Fastcash().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel BalLbl;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton GoBackBtn;
    private javax.swing.JButton W10000Btn;
    private javax.swing.JButton W1000Btn;
    private javax.swing.JButton W100Btn;
    private javax.swing.JButton W2000Btn;
    private javax.swing.JButton W5000Btn;
    private javax.swing.JButton W500Btn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    // End of variables declaration//GEN-END:variables
}
